### ISSUE TITLE
bug?: QuickStart not working in NodeJS 18

### ISSUE THREAD

**Issue by Erb3** [tmpim/krist.js#1]
Following the quick start guide in krist.js docs:
```js
import { KristApi } from "krist";
const api = new KristApi();
```
Will not work. Trying to run it will result in:

```error
import { KristApi } from "krist";
         ^^^^^^^^
SyntaxError: Named export 'KristApi' not found. The requested module 'krist' is a CommonJS module, which may not support all module.exports as named exports.
```

I am assuming that this is a bug, and that it is not me just being dumb.

|                         |                |
|-----------------|----------|
| NodeJS version | v18.12.1 |
| Krist.js version  | v2.0.1     |

Oh, and I use `type`: `module`

**Comment by Lemmmy** [comment]
Sorry for the delay, our builds weren't perfectly compatible with ES modules for various reasons. Please try again with 3.0.0 and re-open if you strill have any issues.
