### ISSUE TITLE
Doesn't compile on latest Typescript

### ISSUE THREAD

**Issue by piprett** [tmpim/krist.js#2]
Hey 👋

I installed krist.js on a project recently, and everything was working fine with `ts-node src/myApp.ts`, but when running `tsc` it did not feel like compiling krist.js.
I have tested around a bit and discovered that krist.js does not compile with Typescript version 5.1.3. I am assuming other versions are affected, but this is what I tested with.

To reproduce (what I did):
1. Create a GitHub codespace with krist.js source
2. Run `npm i -D typescript@5.1.3`
3. Try to compile by running `npx tsc`

You can do the repoduction steps above without GitHub codespaces, but that is what I used when double-checking that it wasn't my code.

**Comment by Lemmmy** [comment]
Do you know what Typescript versions _do_ work?

**Comment by Lustyn** [comment]
Well, of course this library isn't going to compile with a version of TypeScript it isn't using. However, that should be a non-issue as when its distributed on npm you shouldn't actually be compiling the code again. The package includes the compiled js and declarations (.d.ts) which are used just for type checking _your_ code.

As a general rule of thumb: if you get errors when compiling _your_ code related to a library you imported, the desirable workaround is to enable `skipLibCheck`: https://www.typescriptlang.org/tsconfig#skipLibCheck.
